coverage:
  status:
    project:
      ngx-i18n-router/core:
        target: 80%
        paths: packages/@ngx-i18n-router/core
    project:
      ngx-i18n-router/http-loader:
        target: 80%
        paths: packages/@ngx-i18n-router/http-loader
    project:
      ngx-i18n-router/config-loader:
        target: 80%
        paths: packages/@ngx-i18n-router/config-loader
